<link href="./css/leftbrain.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="./js/leftBrain/Concept.js"></script>
<script type="text/javascript" src="./js/leftBrain/VerbBranch.js"></script>
<script type="text/javascript" src="./js/leftBrain/ConceptNameMapper.js"></script>
<script type="text/javascript" src="./js/leftBrain/TautologyManager.js"></script>
<script type="text/javascript" src="./js/leftBrain/Instinct.js"></script>
<script type="text/javascript" src="./js/leftBrain/Statement.js"></script>
<script type="text/javascript" src="./js/leftBrain/ComplementaryOperatorManager.js"></script>
<script type="text/javascript" src="./js/leftBrain/MutuallyExclusiveOperatorManager.js"></script>
<script type="text/javascript" src="./js/leftBrain/EvaluationCache.js"></script>
<script type="text/javascript" src="./js/leftBrain/ProofCache.js"></script>
<script type="text/javascript" src="./js/leftBrain/Flattenizer.js"></script>
<script type="text/javascript" src="./js/leftBrain/Optimizer.js"></script>
<script type="text/javascript" src="./js/leftBrain/Invalidator.js"></script>
<script type="text/javascript" src="./js/leftBrain/ProofManager.js"></script>
<script type="text/javascript" src="./js/leftBrain/ThinkerGeneralizationToParent.js"></script>
<script type="text/javascript" src="./js/leftBrain/ThinkerGeneralizationToBrother.js"></script>
<script type="text/javascript" src="./js/leftBrain/ThinkerFindParentOfEnemyBrother.js"></script>
<script type="text/javascript" src="./js/leftBrain/ThinkerFindEnemyBrother.js"></script>
<script type="text/javascript" src="./js/leftBrain/Thinker.js"></script>
<script type="text/javascript" src="./js/leftBrain/Theory.js"></script>
<script type="text/javascript" src="./js/leftBrain/WhatisViewer.js"></script>
<script type="text/javascript" src="./js/leftBrain/DefineViewer.js"></script>
<script type="text/javascript" src="./js/leftBrain/TeachViewer.js"></script>
<script type="text/javascript" src="./js/leftBrain/ObjectionFinder.js"></script>
<script type="text/javascript" src="./js/leftBrain/FirstSecondPersonManager.js"></script>
<script type="text/javascript" src="./js/leftBrain/HumanStatementSplitter.js"></script>
<script type="text/javascript" src="./js/leftBrain/HumanStatementColorizer.js"></script>
<script type="text/javascript" src="./js/leftBrain/AskViewer.js"></script>
<script type="text/javascript" src="./js/leftBrain/History.js"></script>
<script type="text/javascript" src="./js/leftBrain/AutoComplete.js"></script>
<script type="text/javascript" src="./js/leftBrain/ConversationManager.js"></script>
<script type="text/javascript" src="./js/leftBrain/TalkingRouter.js"></script>